version: "1.0"
info:
  model: int-scaffold
packages:
- name: Insrsa_playProject
  gitServerName: insrsa_github
  gitUrl: https://github.com/chini007/Insrsa_playProject
  gitUsername: chini007
  gitBranch: dev
