version: "1.0"
info:
  model: int-scaffold
packages:
- name: Insrsa_playProject
  gitServerName: insrsa_github
  gitUrl: https://github.com/chini007/Insrsa_playProject
  gitUsername: chini007
  gitBranch: dev
- name: SupportPkg
  gitServerName: insrsa_github
  gitUrl: https://github.com/chini007
  gitUsername: chini007
  gitBranch: dev
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
services:
- serviceName: project.insrsa_play.integrations:routing_b
  packages:
  - name: Insrsa_playProject
    version: "1.0"
  - name: SupportPkg
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.insrsa_play.integrations:DMG_map1
  packages:
  - name: Insrsa_playProject
    version: "1.0"
  - name: SupportPkg
    version: "1.0"
- serviceName: project.insrsa_play.integrations:sampleES
  packages:
  - name: Insrsa_playProject
    version: "1.0"
  - name: SupportPkg
    version: "1.0"
- serviceName: SupportPkg.utils:supportService
  packages:
  - name: SupportPkg
    version: "1.0"
- serviceName: pub.xml:xmlStringToXMLNode
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.xml:xmlNodeToDocument
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:MySql_Edge
  packages:
  - name: Insrsa_playProject
    version: "1.0"
  - name: SupportPkg
    version: "1.0"
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getAllNames
  packages:
  - name: Insrsa_playProject
    version: "1.0"
  - name: SupportPkg
    version: "1.0"
- serviceName: project.insrsa_play.integrations:SoapConsumer
  packages:
  - name: Insrsa_playProject
    version: "1.0"
  - name: SupportPkg
    version: "1.0"
configurationVariables:
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.user
  : sag
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.keyStore
  : ""
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionEnabled
  : "false"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.password
  : "{AES}Y5IgMqjfvkgbg7p5VUZztw=="
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.driverType
  : MySQL_Driver
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.trustStore
  : ""
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.dbType
  : MySQL
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.databaseName
  : sampleDB
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.serverName
  : localdb.orb.local
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.portNumber
  : "3306"
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.networkProtocol
  : tcp
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Insrsa_playProject.project.insrsa_play.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.MySql_Edge.connectionManagerSettings.poolable
  : "false"
